Repository luna/enso, pull requests merged in 2020-02, with the labels that each got.

#482 JSON RPC base actor
  build.sbt
  engine/json-rpc-server/src/main/scala/org/enso/jsonrpcserver/JsonProtocol.scala
  engine/json-rpc-server/src/main/scala/org/enso/jsonrpcserver/MessageHandler.scala
  engine/json-rpc-server/src/main/scala/org/enso/jsonrpcserver/Protocol.scala
  engine/json-rpc-server/src/test/scala/org/enso/jsonrpcserver/MessageHandlerTest.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#480 Core Smart Constructors
  build.sbt
  common/graph/src/main/scala/org/enso/graph/Graph.scala
  common/graph/src/main/scala/org/enso/graph/definition/Macro.scala
  common/graph/src/test/scala/org/enso/graph/GraphTest.scala
  common/graph/src/test/scala/org/enso/graph/GraphTestDefinition.scala
  common/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
  engine/core-definition/src/main/scala/org/enso/core/CoreGraph.scala
  engine/runtime/src/bench/scala/org/enso/compiler/bench/.gitkeep
  engine/runtime/src/main/scala/org/enso/compiler/core/Core.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/CorePrimTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/CoreTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/SmartConstructorsTest.scala
Labels: Category: Compiler, Category: Core, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#481 Update to Scala 2.13.1
  azure-pipelines.yml
  build.sbt
  common/file-manager/src/main/scala/org/enso/FileManager.scala
  common/file-manager/src/main/scala/org/enso/filemanager/API.scala
  common/file-manager/src/test/scala/org/enso/filemanager/BehaviorTests.scala
  common/file-manager/src/test/scala/org/enso/filemanager/Helpers.scala
  common/file-manager/src/test/scala/org/enso/filemanager/WatchTests.scala
  common/flexer/src/main/scala/org/enso/flexer/Parser.scala
  common/flexer/src/main/scala/org/enso/flexer/automata/NFA.scala
  common/flexer/src/main/scala/org/enso/flexer/automata/State.scala
  common/graph/src/main/scala/org/enso/graph/Graph.scala
  common/graph/src/test/scala/org/enso/graph/ComponentMacroTest.scala
  common/graph/src/test/scala/org/enso/graph/FieldMacroTest.scala
  common/graph/src/test/scala/org/enso/graph/GraphTest.scala
  common/graph/src/test/scala/org/enso/graph/GraphTestDefinition.scala
  common/graph/src/test/scala/org/enso/graph/OpaqueMacroTest.scala
  common/graph/src/test/scala/org/enso/graph/TypeFunctionTest.scala
  common/logger/src/main/scala/org/enso/Logger.scala
  common/parser-service/src/main/scala/org/enso/ParserService.scala
  common/parser-service/src/main/scala/org/enso/parserservice/Server.scala
  common/pkg/src/main/scala/org/enso/pkg/Package.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/Server.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/services/ProjectsService.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/services/TutorialsDownloader.scala
  common/syntax/definition/src/main/scala/org/enso/data/Tree.scala
  common/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  common/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Repr2.scala
  common/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Pattern.scala
  common/syntax/definition/src/main/scala/org/enso/syntax/text/ast/text/Escape.scala
  common/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParser.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
  common/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
  common/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala
  engine/gateway/src/main/scala/org/enso/gateway/Server.scala
  engine/gateway/src/test/scala/org/enso/gateway/GatewayJsonSpec.scala
  engine/gateway/src/test/scala/org/enso/gateway/GatewayMessageSpec.scala
  engine/json-rpc-server/src/test/scala/org/enso/jsonrpcserver/MessageHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/LanguageServerSpec.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/Module.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/TopScope.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ApiTest.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/JupyterKernel.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runner/src/main/scala/org/enso/runner/Repl.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/RegressionTest.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/AtomFixtures.scala
  engine/runtime/src/main/java/org/enso/interpreter/util/ScalaConversions.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/OldAST.scala
  engine/runtime/src/main/scala/org/enso/compiler/generate/AstToAstExpression.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/SmartConstructorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ValueExtractorTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
Labels: Category: External, Change: Breaking, Difficulty: Intermediate, Priority: High, Type: Enhancement

#489 Core Tests
  build.sbt
  common/graph/src/main/scala/org/enso/graph/Graph.scala
  common/graph/src/main/scala/org/enso/graph/definition/Macro.scala
  common/graph/src/test/scala/org/enso/graph/GraphTestDefinition.scala
  engine/core-definition/src/main/scala/org/enso/core/CoreGraph.scala
  engine/json-rpc-server/src/test/scala/org/enso/jsonrpcserver/MessageHandlerTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/Pass.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/Core.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/CorePrimTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/CoreTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/SmartConstructorsTest.scala
Labels: Category: Core, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#519 Pass id map to parser calls.
  common/parser-service/src/main/scala/org/enso/ParserService.scala
  common/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
  common/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Backend, Category: Syntax, Change: Non-Breaking, Difficulty: Hard, Priority: High, Type: Enhancement

#521 IR Cleanup
  build.sbt
  engine/core-definition/src/main/scala/org/enso/core/CoreGraph.scala
  engine/runtime/src/main/java/org/enso/interpreter/builder/ArgDefinitionFactory.java
  engine/runtime/src/main/java/org/enso/interpreter/builder/CallArgFactory.java
  engine/runtime/src/main/java/org/enso/interpreter/builder/ExpressionFactory.java
  engine/runtime/src/main/java/org/enso/interpreter/builder/ModuleScopeExpressionFactory.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/OldAST.scala
  engine/runtime/src/main/scala/org/enso/compiler/generate/AstToAstExpression.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaArgumentsTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#554 Engine Protocol Specification
  doc/design/engine/engine-services.md
Labels: Category: Backend, Category: Documentation, Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#555 Capabilities system & canEdit capability
  engine/language-server/src/main/scala/org/enso/languageserver/Client.scala
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/WebSocketServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Capability.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Client.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Environment.scala
  engine/language-server/src/main/scala/org/enso/languageserver/jsonrpc/Protocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/MessageHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/WebSocketServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#556 Pass id map to parser calls.
  common/parser-service/src/main/scala/org/enso/ParserService.scala
  common/syntax/definition/src/main/scala/org/enso/data/Index.scala
  common/syntax/definition/src/main/scala/org/enso/data/Span.scala
  common/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Intermediate, Priority: Highest, Type: Enhancement

#558 Fixed Nested Serialization on the Parser Service Request Format
  common/parser-service/src/main/scala/org/enso/ParserService.scala
  common/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#559 File Reads for the Language Server
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
  engine/language-server/src/test/scala/org/enso/languageserver/WebSocketServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#560 File Creates for the Language Server
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemObject.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/Path.scala
  engine/language-server/src/test/scala/org/enso/languageserver/WebSocketServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#561 Rope data structure
  build.sbt
  engine/language-server/src/bench/scala/org/enso/languageserver/buffer/RopeBench.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/CharView.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/CodePointView.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/LineView.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/Rope.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/StringUtils.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/Tree.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/TreeOps.scala
  engine/language-server/src/test/scala/org/enso/languageserver/buffer/Generators.scala
  engine/language-server/src/test/scala/org/enso/languageserver/buffer/MockBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/buffer/RopeSpecification.scala
  engine/language-server/src/test/scala/org/enso/languageserver/buffer/StringUtilsSpecification.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Unknown, Priority: Highest, Type: Enhancement
