Repository luna/enso, pull requests merged in 2020-05, with the labels that each got.

#705 Paying off some Technical Debt
  .scalafmt.conf
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/RedefinedMethodException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/DependentMap.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/ir/MetadataStorage.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/PassConfiguration.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LiftSpecialOperators.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIRTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/FreshNameSupplyTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/IRTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/ir/MetadataStorageTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/PassConfigurationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaChainingTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
Labels: Category: Compiler, Category: Interpreter, Category: Semantics, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#706 Upload the FlatBuffers Schemas to S3
  .github/workflows/scala.yml
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#710 Fix polymorphic frame slot writes
  engine/runtime/src/main/java/org/enso/interpreter/node/scope/AssignmentNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/scope/ReadLocalVariableNode.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#709 Add PoC of Caching Injection to IdExecutionInstrument
  engine/runtime/src/main/java/org/enso/interpreter/instrument/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeServerInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/ValueOverrideInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/IdeWorkflowTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ValueOverrideTest.scala
Labels: Category: Compiler, Category: Interpreter, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#711 Truffle Integration for the Binary Protocol
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/BinaryConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/factory/VisualisationUpdateFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/visualisation/AttachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/visualisation/DetachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/visualisation/ModifyVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/VisualisationProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/AttachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/DetachVisualisationHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/ModifyVisualisationHandler.scala
  engine/language-server/src/main/schema/envelope.fbs
  engine/language-server/src/main/schema/execution_context.fbs
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/VisualisationProtocolTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContext.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContextManager.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContextState.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Visualisation.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/VisualisationHolder.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#712 Review of the Language Server Spec
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/scala/org/enso/languageserver/data/Capability.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemObject.scala
  engine/language-server/src/main/scala/org/enso/languageserver/http/server/BinaryWebSocketServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/rpc/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/CreateHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/ExecutionContextJsonMessages.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/FileNotificationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/ReceivesTreeUpdatesHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/TextOperationsTest.scala
Labels: Category: Backend, Category: Documentation, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Bug

#716 Add More Syntactic Support
  build.sbt
  doc/types/design/types.md
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/RedefinedMethodException.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LiftSpecialOperators.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/SectionsToBinOp.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/.gitkeep
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/OverloadsResolution.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIRTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LiftSpecialOperatorsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/UnusedBindingsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/IgnoredBindingsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/OverloadsResolutionTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaShorthandArgsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OperatorSectionsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OverloadsResolutionErrorTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StrictCompileDiagnosticsTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#718 Fix Typo in Interpreter Package Name
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeServerInstrument.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/ExecutionContextManager.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/ExecutionContextState.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Visualisation.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/VisualisationHolder.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Beginner, Priority: Low, Type: Enhancement

#723 Java and Polyglot utility functions
  engine/runtime/src/main/java/org/enso/interpreter/Constants.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Execute0Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Execute1Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Execute2Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetArrayElementNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetArraySizeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetMemberNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/GetMembersNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Instantiate0Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Instantiate1Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Instantiate2Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/java/AddToClassPathNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/java/LookupClassNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/NanoTimeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/test/java/org/enso/example/TestClass.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#725 Design Doc Updates
  doc/runtime/implementation/polyglot/java.md
  doc/runtime/implementation/polyglot/polyglot.md
  doc/semantics/implementation/.gitkeep
  doc/semantics/implementation/scoping.md
  doc/semantics/specification/polyglot.md
  doc/semantics/specification/semantics.md
  doc/syntax/specification/polyglot.md
  doc/syntax/specification/syntax.md
  doc/types/design/polyglot.md
  doc/types/design/types.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#726 Update Language Server Spec
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/CreateHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/ExecutionContextJsonMessages.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Documentation, Change: Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#728 List Literals
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/SequenceLiteralNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Execute0Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/ExecuteNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Instantiate1Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/Instantiate2Node.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/InstantiateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/generic/InvokeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/data/Vector.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaShorthandArgsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/NamedArgumentsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SequenceLiteralsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SuspendedArgumentsTest.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#727 Binary File Support
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/BinaryConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/BinaryConnectionControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/factory/ErrorFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/factory/FileContentsReplyFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/factory/SessionInitResponseFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/data/factory/SuccessReplyFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/rpc/RpcConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/rpc/RpcConnectionControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadBinaryFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadTextualFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteBinaryFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteTextualFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/util/file/PathUtils.scala
  engine/language-server/src/main/scala/org/enso/languageserver/util/file/UuidUtils.scala
  engine/language-server/src/main/schema/envelope.fbs
  engine/language-server/src/main/schema/file_manager.fbs
  engine/language-server/src/main/schema/session.fbs
  engine/language-server/src/main/schema/util.fbs
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/BaseBinaryServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/BinaryFileManipulationTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/BinarySessionManagementTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/VisualisationProtocolTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/factory/PathFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/factory/ReadFileCommandFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/factory/SessionInitFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/factory/WriteFileCommandFactory.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/BaseServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#739 Syntactic Java integration
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/ConstructorDispatchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/interop/syntax/MethodDispatchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/ConstantObjectNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/JavaInteropTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/PolyglotTest.scala
  lib/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
Labels: Category: Interpreter, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#740 Documentation Updates
  doc/runtime/design/runtime.md
  doc/runtime/implementation/polyglot/java.md
  doc/semantics/specification/semantics.md
  doc/syntax/design/.gitkeep
  doc/syntax/design/syntax.md
  doc/syntax/specification/syntax.md
  doc/types/design/types.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#736 Use the Text Diff to Work Out the Changeset
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/DiffChangeset.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/DiffChangesetTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#743 Perform Dependency Analysis in terms of External IDs
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#744 Enso package and distribution specifications
  doc/distribution/design/packaging.md
  doc/distribution/implementation/distribution.md
  doc/distribution/specification/distribution.md
  doc/distribution/specification/packaging.md
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#746 Add a Hack for Unary Minus
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NegateNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NumberBinaryOpMethod.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LambdaShorthandArgsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/OperatorSectionsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/SimpleArithmeticTest.scala
Labels: Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#742 Add Error Handling to Execution Context
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#745 Project Manager package
  .github/workflows/scala.yml
  build.sbt
  lib/project-manager/src/main/resources/application.conf
  lib/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerBootLoader.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistry.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisor.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/protocol/ManagerClientControllerFactory.scala
Labels: Category: External, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#738 Assign a UUID to Each AST Node
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
  lib/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#754 Implement `print_err` and `readln`
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintErrNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/PrintlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/io/ReadlnNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/system/NanoTimeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
  lib/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala
Labels: Category: Libraries, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#763 Add workflow to update `luna.github.io` on docs push
  .github/workflows/docs.yml
Labels: Category: Build, Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#765 Add Syntax Sugar for Defining Functions and Methods
  engine/polyglot-api/src/main/java/org/enso/polyglot/MethodNames.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ClosureRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/OverloadsResolutionTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/FunctionSugarTest.scala
Labels: Category: Compiler, Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#770 Miscellaneous Documentation Fixes
  .github/settings.yml
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/README.md
  docs/language-server/README.md
  docs/rfcs/0001-rfc-template.md
  docs/rfcs/README.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#764 Add the Runtime Cache Design Docs
  docs/runtime/caching.md
Labels: Category: Compiler, Category: RTS, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#771 Auto-imported Std Lib and File Operations Cleanup
  .github/workflows/scala.yml
  distribution/lib/Base/0.0.1/src/Maybe.enso
  distribution/package-sets/default.yaml
  distribution/std-lib/Base/package.yaml
  distribution/std-lib/Base/src/Boolean.enso
  distribution/std-lib/Base/src/Maybe.enso
  docs/distribution/distribution.md
  docs/distribution/packaging.md
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/OptionsHelper.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/util/TruffleFileSystem.java
  engine/runtime/src/test/resources/TestNonImportedOverloads/package.yaml
  engine/runtime/src/test/resources/TestNonImportedOwnMethods/package.yaml
  engine/runtime/src/test/resources/TestSimpleImports/package.yaml
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/pkg/src/main/scala/org/enso/filesystem/FileSystem.scala
  lib/pkg/src/main/scala/org/enso/home/HomeManager.scala
  lib/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/pkg/src/main/scala/org/enso/pkg/Main.scala
  lib/pkg/src/main/scala/org/enso/pkg/Package.scala
  lib/pkg/src/main/scala/org/enso/pkg/QualifiedName.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
Labels: Category: Compiler, Category: Distribution, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#773 Implement Support for Complex Type Definitions
  docs/style-guide/haskell.md
  docs/style-guide/java.md
  docs/style-guide/rust.md
  docs/style-guide/scala.md
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ComplexTypeDefinitionSugarTest.scala
Labels: Category: Compiler, Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#768 Add FlakySpec Test Suite
  engine/language-server/src/test/scala/org/enso/languageserver/requesthandler/monitoring/PingHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BinaryFileManipulationTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/BinarySessionManagementTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/binary/VisualisationProtocolTest.scala
  lib/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/FlakySpec.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisorSpec.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Beginner, Priority: Medium, Type: Enhancement

#772 Input/Output Stream Redirection
  docs/language-server/protocol-language-server.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/ExecutionContextEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/SessionEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/InputOutputApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/InputOutputProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/InputRedirectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/ObservableOutputStream.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/ObservablePipedInputStream.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/OutputKind.scala
  engine/language-server/src/main/scala/org/enso/languageserver/io/OutputRedirectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/binary/BinaryConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonConnectionControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/json/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/io/FeedStandardInputHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/io/RedirectStdErrHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/io/RedirectStdOutHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/io/SuppressStdErrHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/io/SuppressStdOutHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/session/SessionRouter.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/json/InputOutputRedirectionTest.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#775 Bump GraalVM to 20.1
  .github/workflows/scala.yml
  build.sbt
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/BranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/CaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/ConstructorBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/DefaultFallbackBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/FallbackBranchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/MatchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/Atom.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
Labels: Category: Build, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#781 Introduce Threaded Executions to the Runtime Server Instrument - Part 1
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/BaseVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CloseFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/Command.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CommandFactory.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/CreateContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/DestroyContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/DetachVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualisationCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/OpenFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PopContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/CommandProcessor.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/PreemptiveCommandProcessor.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/RuntimeContext.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/TruffleThreadFactory.scala
  lib/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonRpcServer.scala
Labels: Category: Backend, Category: Tooling, Change: Breaking, Difficulty: Core Contributor, Priority: Highest

#778 Implement the Runtime Cache
  engine/runtime/src/bench/java/org/enso/interpreter/bench/benchmarks/RuntimeCacheBenchmarks.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/Cache.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeCache.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/Changeset.scala
  engine/runtime/src/main/scala/org/enso/compiler/context/FreshNameSupply.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/CacheInvalidation.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/ExecutionContextManager.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/ExecutionContextState.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PopContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/ProgramExecutionSupport.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/PushContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/RecomputeContextCmd.scala
  engine/runtime/src/main/scala/org/enso/interpreter/instrument/execution/RuntimeContext.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/context/ChangesetTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeCacheTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Backend, Category: Interpreter, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#786 Verify Pass Dependencies
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/PassManager.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherDiagnostics.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/ComplexType.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LambdaShorthandToLambda.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/SectionsToBinOp.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/lint/UnusedBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/LambdaConsolidate.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/IgnoredBindings.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/OverloadsResolution.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/core/ir/MetadataStorageTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/PassConfigurationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/PassManagerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherDiagnosticsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/FunctionBindingTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LambdaShorthandToLambdaTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/SectionsToBinOpTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/lint/UnusedBindingsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/optimise/LambdaConsolidateTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/IgnoredBindingsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/OverloadsResolutionTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#780 Handles disable and doc comments
  docs/syntax/comments.md
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Passes.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIr.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/ir/MetadataStorage.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/FunctionBinding.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/DocumentationComments.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/PassesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/codegen/AstToIrTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/ComplexTypeTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/resolve/DocumentationCommentsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CommentsTest.scala
  lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/CommentRemover.scala
  lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
  lib/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala
Labels: Category: Compiler, Category: Syntax, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#779 Describe the Internal Execution Queue in Runtime Server
  docs/runtime/execution-server-flow.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
