Repository luna/enso, pull requests merged in 2020-03, with the labels that each got.

#566 Artefact Builds for the Language Server
  azure-pipelines.yml
  build.sbt
  engine/runner/src/main/scala/org/enso/runner/LanguageServerApp.scala
  engine/runner/src/main/scala/org/enso/runner/LanguageServerConfig.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: Category: Backend, Category: External, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#568 Add file/delete message
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/WebSocketServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#573 Update CI Images
  azure-pipelines.yml
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#572 Execution API spec
  doc/design/engine/engine-services.md
Labels: Category: Backend, Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Discussion

#570 Add file/copy message to language server
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#578 Update readme to make it consistent with one in IDE repository
  README.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium

#580 Further update of README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Medium

#576 Update GraalVM to 20.0.0
  azure-pipelines.yml
  build.sbt
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  project/WithDebugCommand.scala
Labels: Category: External, Change: Breaking, Difficulty: Intermediate, Priority: Low, Type: Enhancement

#575 text/openFile method
  CONTRIBUTING.md
  build.sbt
  common/file-manager/src/test/scala/org/enso/filemanager/WatchTests.scala
  doc/design/engine/engine-services.md
  engine/language-server/src/bench/scala/org/enso/languageserver/text/RopeBench.scala
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServerConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/WebSocketServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityRouter.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Capability.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Client.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/ContentBasedVersioning.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Environment.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Sha3_224VersionCalculator.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/BufferEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/ClientEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/Event.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/AcquireCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/OpenFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/ReleaseCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/RequestTimeout.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/data/Sha3224VersionCalculatorSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/Generators.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/MockBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/RopeSpecification.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/StringUtilsSpecification.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/CapabilitiesTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/TextOperationsTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/WebSocketServerTest.scala
  engine/runner/src/main/scala/org/enso/runner/LanguageServerApp.scala
  engine/runner/src/main/scala/org/enso/runner/LanguageServerConfig.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#581 Desugar Operators to Functions
  doc/design/syntax/syntax.md
  engine/core-definition/src/main/scala/org/enso/core/CoreGraph.scala
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/analysis/.gitkeep
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/AddNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/DivideNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/ModNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/MultiplyNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NumberBinaryOpMethod.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/SubtractNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/operator/AddOperatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/operator/SubtractOperatorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIR.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/.gitkeep
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/.gitkeep
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LiftSpecialOperators.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/optimise/.gitkeep
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LiftSpecialOperatorsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#582 Add a CI check of artifact validity.
  azure-pipelines.yml
  ci/Test.enso
Labels: Category: External, Change: Non-Breaking, Difficulty: Unknown, Priority: Highest, Type: Enhancement

#583 text/closeFile method
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/BufferEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/CloseFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/TextOperationsTest.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#579 Add file/exists message to language server
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#574 Add file/move message to language server
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#584 Add a `--version` Flag for the CLI
  .github/ISSUE_TEMPLATE/bug-report.md
  azure-pipelines.yml
  build.sbt
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  project/BuildInfo.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#577 Parser Attaching Ids to Expressions
  common/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Tooling, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#596 Add documentation for Documentation Parser
  doc/design/syntax/syntax.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium

#598 `text/applyEdit` method
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/ApplyEditHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/editing/EditorOps.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/editing/RopeTextEditor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/editing/TextEditValidationFailure.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/editing/TextEditValidator.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/editing/TextEditor.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/editing/model.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/editing/EditorOpsSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/editing/RopeTextEditorSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/editing/TestData.scala
  engine/language-server/src/test/scala/org/enso/languageserver/text/editing/TextEditValidatorSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/TextOperationsTest.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#586 Store idmap with metadata in source file.
  common/parser-service/src/main/scala/org/enso/ParserService.scala
  common/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
  common/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  common/syntax/specialization/shared/src/bench/scala/org/enso/syntax/ParserBenchmark.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
  common/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#602 Create a server instrument for language server <> runtime communications
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/WebSocketServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/WebSocketServerTest.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeServerInfo.java
  engine/polyglot-api/src/main/scala/org/enso/polyglot/RuntimeApi.scala
  engine/runner/src/main/scala/org/enso/runner/LanguageServerApp.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/ReplDebuggerInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeServerInstrument.java
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Hard, Priority: Highest, Type: Enhancement

#604 Fix parsing of metadata.
  common/parser-service/src/main/scala/org/enso/ParserService.scala
  common/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
  common/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#585 Add file/tree message for language server
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/DirectoryTree.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailure.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemObject.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/Path.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/TextOperationsTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#595 Fix for Parser Giving Ids
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#610 Scaffold the Project Manager
  build.sbt
  common/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  common/json-rpc-server/src/main/scala/org/enso/jsonrpc/ClientControllerFactory.scala
  common/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonProtocol.scala
  common/json-rpc-server/src/main/scala/org/enso/jsonrpc/JsonRpcServer.scala
  common/json-rpc-server/src/main/scala/org/enso/jsonrpc/MessageHandler.scala
  common/json-rpc-server/src/main/scala/org/enso/jsonrpc/Protocol.scala
  common/json-rpc-server/src/test/scala/org/enso/jsonrpc/MessageHandlerSpec.scala
  common/project-manager/src/main/resources/application.conf
  common/project-manager/src/main/scala/org/enso/projectmanager/RouteHelper.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/Server.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/api/Project.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/main/MainModule.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/main/ProjectManager.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/main/configuration.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/ManagerClientControllerFactory.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ServerClientControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/AcquireCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/ApplyEditHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/CloseFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/OpenFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/ReleaseCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/SaveFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/TextOperationsTest.scala
  engine/runner/src/main/scala/org/enso/runner/LanguageServerApp.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#609 Refactor FileManager file commands
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Environment.scala
  engine/language-server/src/main/scala/org/enso/languageserver/effect/Exec.scala
  engine/language-server/src/main/scala/org/enso/languageserver/effect/package.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ServerClientControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/CopyFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/CreateFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/DeleteFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ExistsFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/MoveFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/TreeFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#611 Execution context management
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/PolyglotContext.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/RuntimeApi.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ApiTest.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/JupyterKernel.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeServerInstrument.java
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContext.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ContextManagementTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#612 Add file/list filemanager command
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ListFileHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#613 Implement Alias Analysis on Core
  build.sbt
  doc/design/semantics/semantics.md
  engine/runtime/src/main/java/org/enso/interpreter/instrument/ReplDebuggerInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/InstantiateAtomNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/AtomConstructor.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/LocalScope.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LiftSpecialOperators.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LiftSpecialOperatorsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ContextManagementTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ReplTest.scala
Labels: Category: Compiler, Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#617 test: wait for FileManager initialization
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#616 Create a Code Generation Pass
  build.sbt
  doc/design/syntax/syntax.md
  engine/runtime/src/main/java/org/enso/interpreter/node/ClosureRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/BlockNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/function/CreateFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/ConstructorCaseNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/controlflow/MatchNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/InlineContext.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIR.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/IRPass.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/GenerateMethodBodies.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/LiftSpecialOperators.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/desugar/OperatorToFunction.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/ApplicationSaturationTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/GenerateMethodBodiesTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LiftSpecialOperatorsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CurryingTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#622 Try and Set Up GH Actions
  .github/workflows/scala.yml
  azure-pipelines.yml
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Lowest, Type: Enhancement

#625 Artifact Builds on All Branches
  .github/workflows/scala.yml
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Low, Type: Enhancement

#624 Remove file manager warmup in tests
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Beginner, Priority: Medium, Type: Enhancement

#614 Add file/info command
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileAttributes.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/Path.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/InfoFileHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#627 Thread IDs through the compiler pipelines
  common/parser-service/src/main/scala/org/enso/ParserService.scala
  common/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  common/syntax/specialization/js/src/main/scala/org/enso/syntax/text/Main.scala
  common/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ExpressionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/tag/IdentifiedTag.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIR.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/test/java/org/enso/interpreter/test/CodeIdsTestInstrument.java
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/LiftSpecialOperatorsTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/desugar/OperatorToFunctionTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ValueExtractorTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ExpressionIdTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#629 Fix parser benchmarks.
  build.sbt
  common/syntax/specialization/shared/src/bench/scala/org/enso/syntax/ParserBenchmark.scala
Labels: Category: Syntax, Change: Non-Breaking, Difficulty: Unknown, Priority: Highest, Type: Bug

#626 Add file/event command
  build.sbt
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityRouter.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Capability.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/effect/Exec.scala
  engine/language-server/src/main/scala/org/enso/languageserver/event/ClientEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileAttributes.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileEvent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystemApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcher.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/PathWatcherProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/WatcherAdapter.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/AcquireCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/ApplyEditHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/CloseFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/OpenFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/ReleaseCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/SaveFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/CopyFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/CreateFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/DeleteFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ExistsFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/InfoFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ListFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/MoveFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/TreeFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/WriteFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/effect/Effects.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/FileSystemSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/WatcherAdapterSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/ReceivesTreeUpdatesHandlerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#631 Implementation of project/open and project/close commands.
  build.sbt
  common/project-manager/src/main/resources/application.conf
  common/project-manager/src/main/resources/logback.xml
  common/project-manager/src/main/scala/org/enso/projectmanager/boot/Globals.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/boot/ZioPlatform.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/control/effect/Async.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/control/effect/ImmediateExecutor.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/control/effect/Sync.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/control/effect/ZioAsync.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/data/SocketData.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/event/ClientEvent.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/event/Event.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerBootLoader.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerDescriptor.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerProtocol.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistry.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistryProxy.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerService.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/net/Tcp.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectRepository.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/main/Globals.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/main/configuration.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/JsonRpc.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/ManagerClientControllerFactory.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectCloseHandler.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectServiceFailureMapper.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceFailure.scala
  common/project-manager/src/test/scala/org/enso/projectmanager/protocol/BaseServerSpec.scala
  common/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerConfig.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/runner/src/main/scala/org/enso/runner/LanguageServerApp.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement
