Repository luna/enso, pull requests merged in 2020-04, with the labels that each got.

#632 Add executionContext/create command
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Capability.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ServerClientControllerFactory.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/CreateHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/CreateContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/ContextRegistryTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ContextManagementTest.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#639 doc: fix engine-services.md format
  doc/design/engine/engine-services.md
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Beginner, Priority: Low, Type: Enhancement

#638 Fixes to CONTRIBUTING.md instructions
  CONTRIBUTING.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Bug

#642 Language Execution Service
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/instrument/RuntimeServerInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/ApplicationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/FunctionCallInstrumentationNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/dispatch/InvokeFunctionNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/Metadata.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ExpressionIdTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#640 Visualisation Protocol Design and Specification
  doc/design/engine/engine-services.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#637 Add executionContext push & pop commands
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PopHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PushHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/MethodPointer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/StackItem.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PopContextHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/PushContextHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/ContextRegistryTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContext.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ContextManagementTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#643 Implementation of the Language Server Supervisor Process
  .github/workflows/scala.yml
  build.sbt
  common/project-manager/src/main/resources/application.conf
  common/project-manager/src/main/scala/org/enso/projectmanager/boot/MainModule.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/boot/configuration.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/data/Socket.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/data/SocketData.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/AkkaBasedWebSocketConnection.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/AkkaBasedWebSocketConnectionFactory.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/FanOutReceiver.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/WebSocketConnection.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/WebSocketConnectionFactory.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/HeartbeatSession.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerBootLoader.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerController.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerProtocol.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistry.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistryProxy.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerService.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisor.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/package.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/protocol/ProjectManagementApi.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  common/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  common/project-manager/src/test/resources/logback-test.xml
  common/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisorSpec.scala
  common/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/PingMatcher.scala
  common/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/ProgrammableWebSocketServer.scala
  common/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/StepParent.scala
  common/project-manager/src/test/scala/org/enso/projectmanager/protocol/BaseServerSpec.scala
  common/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
  doc/design/engine/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/LanguageServer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LifecycleComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/capability/CapabilityRouter.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/monitoring/MonitoringApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/monitoring/MonitoringProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/monitoring/PingHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/test/scala/org/enso/languageserver/requesthandler/monitoring/PingHandlerSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/MonitoringTest.scala
  project/build.properties
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#641 Actions Tweaks
  .github/workflows/scala.yml
  .scalafmt.conf
  project/build.properties
Labels: Category: External, Change: Non-Breaking, Difficulty: Hard, Priority: High, Type: Enhancement

#648 Add executionContext/expressionValuesComputed notifincation
  doc/engine/specification/engine-services.md
  engine/language-server/src/main/scala/org/enso/languageserver/data/Config.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/CreateHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/DestroyHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PopHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/PushHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExpressionValueUpdate.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/ContextRegistryTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#649 Implementation of session initialisation
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/capability/AcquireCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/capability/ReleaseCapabilityHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/session/InitProtocolConnectionHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/ApplyEditHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/CloseFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/OpenFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/text/SaveFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/session/SessionApi.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/ContextRegistryTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileManagerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/ReceivesTreeUpdatesHandlerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/SessionManagementTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/TextOperationsTest.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/protocol/ProjectManagementApiSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#654 Another Attempt at Fixing Caching on CI
  .github/workflows/scala.yml
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Medium, Type: Enhancement

#647 [AST] Fixed ozipBlock
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
Labels: Category: Tooling, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#659 Move visualisationUpdate to more appropriate place
  doc/language-server/specification/enso-protocol.md
Labels: Category: Documentation, Change: Non-Breaking, Difficulty: Beginner, Priority: Lowest, Type: Bug

#658 Implement Demand Analysis
  doc/README.md
  doc/enso-philosophy.md
  doc/runtime/specification/.gitkeep
  doc/runtime/specification/demand-analysis.md
  doc/semantics/specification/semantics.md
  engine/runtime/src/bench/scala/org/enso/interpreter/bench/fixtures/semantic/RecursionFixtures.scala
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIR.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstView.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DemandAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CodeLocationsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/ExpressionIdTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/GlobalScopeTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/GroupingTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/LazyArgumentsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StateTest.scala
Labels: Category: Compiler, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#655 Flatbuffers integration
  .github/workflows/scala.yml
  CONTRIBUTING.md
  build.sbt
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/schema/execution-context.fbs
  engine/language-server/src/main/schema/protocol.fbs
  engine/language-server/src/main/schema/session.fbs
  engine/language-server/src/main/schema/util.fbs
  lib/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  project/GenerateFlatbuffers.scala
Labels: Category: External, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#661 Format projects with scalafmt
  engine/language-server/src/main/scala/org/enso/languageserver/boot/LanguageServerComponent.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/Rope.scala
  engine/language-server/src/main/scala/org/enso/languageserver/data/buffer/Tree.scala
  engine/language-server/src/main/scala/org/enso/languageserver/effect/Exec.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileSystem.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/JupyterKernel.scala
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/Core.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/TailCallTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ContextManagementTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/IdeWorkflowTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ValueExtractorTest.scala
  lib/file-manager/src/main/scala/org/enso/FileManager.scala
  lib/file-manager/src/main/scala/org/enso/filemanager/API.scala
  lib/file-manager/src/test/scala/org/enso/filemanager/Helpers.scala
  lib/file-manager/src/test/scala/org/enso/filemanager/WatchTests.scala
  lib/flexer/src/main/scala/org/enso/flexer/ADT.scala
  lib/flexer/src/main/scala/org/enso/flexer/automata/Pattern.scala
  lib/flexer/src/main/scala/org/enso/flexer/automata/State.scala
  lib/graph/src/main/scala/org/enso/graph/definition/Macro.scala
  lib/graph/src/test/scala/org/enso/graph/ComponentMacroTest.scala
  lib/graph/src/test/scala/org/enso/graph/GraphTestDefinition.scala
  lib/graph/src/test/scala/org/enso/graph/OpaqueMacroTest.scala
  lib/graph/src/test/scala/org/enso/graph/TypeFunctionTest.scala
  lib/parser-service/src/main/scala/org/enso/ParserService.scala
  lib/parser-service/src/main/scala/org/enso/parserservice/Protocol.scala
  lib/parser-service/src/main/scala/org/enso/parserservice/Server.scala
  lib/pkg/src/main/scala/org/enso/pkg/Config.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/control/effect/ZioAsync.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/AkkaBasedWebSocketConnection.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/ProjectFileRepository.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/repository/package.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/protocol/ClientController.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectListRecentHandler.scala
  lib/syntax/definition/src/main/scala/org/enso/data/List1.scala
  lib/syntax/definition/src/main/scala/org/enso/data/Size.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Doc.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Repr.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Repr2.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/Repr3.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builder.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Builtin.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Pattern.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/prec/Macro.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/spec/DocParserDef.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/spec/ParserDef.scala
  lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/DocParser.scala
  lib/syntax/specialization/shared/src/main/scala/org/enso/syntax/text/Parser.scala
  lib/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/DocParserTests.scala
  lib/syntax/specialization/shared/src/test/scala/org/enso/syntax/text/ParserTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Beginner, Priority: Low, Type: Enhancement

#657 Impl: Execution Context Management Integration
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/monitoring/PingHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeFailureMapper.scala
  engine/language-server/src/test/scala/org/enso/languageserver/filemanager/WatcherAdapterSpec.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/ContextRegistryTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/type/Types.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContext.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/ContextManagementTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#660 Module file operations through execution server.
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/FileEdit.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/TextProtocol.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/Language.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ProgramRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  lib/text-buffer/src/main/scala/org/enso/text/buffer/CharView.scala
  lib/text-buffer/src/main/scala/org/enso/text/buffer/CodePointView.scala
  lib/text-buffer/src/main/scala/org/enso/text/buffer/LineView.scala
  lib/text-buffer/src/main/scala/org/enso/text/buffer/Rope.scala
  lib/text-buffer/src/main/scala/org/enso/text/buffer/StringUtils.scala
  lib/text-buffer/src/main/scala/org/enso/text/buffer/Tree.scala
  lib/text-buffer/src/main/scala/org/enso/text/buffer/TreeOps.scala
  lib/text-buffer/src/main/scala/org/enso/text/editing/EditorOps.scala
  lib/text-buffer/src/main/scala/org/enso/text/editing/JavaEditorAdapter.scala
  lib/text-buffer/src/main/scala/org/enso/text/editing/RopeTextEditor.scala
  lib/text-buffer/src/main/scala/org/enso/text/editing/TextEditValidationFailure.scala
  lib/text-buffer/src/main/scala/org/enso/text/editing/TextEditValidator.scala
  lib/text-buffer/src/main/scala/org/enso/text/editing/TextEditor.scala
  lib/text-buffer/src/main/scala/org/enso/text/editing/model.scala
  lib/text-buffer/src/test/scala/org/enso/text/Generators.scala
  lib/text-buffer/src/test/scala/org/enso/text/MockBuffer.scala
  lib/text-buffer/src/test/scala/org/enso/text/RopeSpecification.scala
  lib/text-buffer/src/test/scala/org/enso/text/StringUtilsSpecification.scala
  lib/text-buffer/src/test/scala/org/enso/text/editing/EditorOpsSpec.scala
  lib/text-buffer/src/test/scala/org/enso/text/editing/RopeTextEditorSpec.scala
  lib/text-buffer/src/test/scala/org/enso/text/editing/TestData.scala
  lib/text-buffer/src/test/scala/org/enso/text/editing/TextEditValidatorSpec.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#667 String concat and string conversion functions
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/MethodResolverNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/number/NumberBinaryOpMethod.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/AnyToTextNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/ConcatNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/TextTest.scala
Labels: Category: Libraries, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#668 Execution Context Integration with Text Change Events
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManager.scala
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/FileManagerProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/file/ReadFileHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextEventsListener.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/Buffer.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/BufferRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/text/CollaborativeBuffer.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/BaseServerTest.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/FileNotificationsTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/ExecutionContext.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#669 Add: executionContext/recompute command
  doc/language-server/specification/enso-protocol.md
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/rpc/ClientController.scala
  engine/language-server/src/main/scala/org/enso/languageserver/protocol/rpc/JsonRpc.scala
  engine/language-server/src/main/scala/org/enso/languageserver/requesthandler/executioncontext/RecomputeHandler.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistry.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ContextRegistryProtocol.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/ExecutionApi.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/InvalidatedExpressions.scala
  engine/language-server/src/main/scala/org/enso/languageserver/runtime/handler/RecomputeContextHandler.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/ContextRegistryTest.scala
  engine/polyglot-api/src/main/scala/org/enso/polyglot/runtime/Runtime.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
Labels: Category: Backend, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Medium, Type: Enhancement

#673 Implement Dependency Analysis
  doc/runtime/specification/caching.md
  engine/language-server/src/main/scala/org/enso/languageserver/http/server/BinaryWebSocketServer.scala
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/ApplicationSaturation.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DataflowAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/DemandAnalysis.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/scope/LocalScope.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/CompilerTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/AliasAnalysisTest.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerBootLoader.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerProtocol.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerRegistryProxy.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerService.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/requesthandler/ProjectOpenHandler.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectService.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/service/ProjectServiceApi.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/PingMatcher.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/Debug.scala
Labels: Category: Compiler, Category: Interpreter, Category: Semantics, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#674 Try Caching Coursier on CI
  .github/PULL_REQUEST_TEMPLATE/pr.md
  .github/workflows/scala.yml
  build.sbt
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/DataflowAnalysisTest.scala
  lib/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  project/build.properties
Labels: Category: External, Change: Non-Breaking, Difficulty: Beginner, Priority: Highest, Type: Enhancement

#687 Compile Error Handling
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/scala.yml
  engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala
  engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeOptions.java
  engine/polyglot-api/src/test/scala/org/enso/polyglot/ModuleManagementTest.scala
  engine/runner/src/main/scala/org/enso/runner/ContextFactory.scala
  engine/runner/src/main/scala/org/enso/runner/Main.scala
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/constant/ErrorNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/AstToIR.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/core/IR.scala
  engine/runtime/src/main/scala/org/enso/compiler/exception/CompilationAbortedException.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherErrors.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/test/scala/org/enso/compiler/test/pass/analyse/GatherErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/InterpreterTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/ValueEquality.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/CompileErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StrictCompileErrorsTest.scala
Labels: Category: Compiler, Category: Core, Category: Interpreter, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#698 Stopgap JSON serialization for Enso objects
  build.sbt
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/text/JsonSerializeNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/scala/org/enso/interpreter/runtime/builtin/LanguageEntitySerializer.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StrictCompileErrorsTest.scala
  engine/runtime/src/test/scala/org/enso/std/test/JsonSerializationTest.scala
Labels: Category: Interpreter, Category: Libraries, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement

#700 Fix double-eval of this argument
  engine/runtime/src/main/java/org/enso/interpreter/node/callable/InvokeCallableNode.java
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/MethodsTest.scala
Labels: Category: Interpreter, Change: Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Bug

#696 Send Information About Function Calls
  engine/runtime/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
  engine/runtime/src/main/java/org/enso/interpreter/node/ClosureRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java
  engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Builtins.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Context.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/ModuleScope.java
  engine/runtime/src/main/java/org/enso/interpreter/runtime/scope/TopLevelScope.java
  engine/runtime/src/main/java/org/enso/interpreter/service/ExecutionService.java
  engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala
  engine/runtime/src/main/scala/org/enso/compiler/codegen/IRToTruffle.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/GatherErrors.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/TailCall.scala
  engine/runtime/src/main/scala/org/enso/interpeter/instrument/Handler.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/PackageTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/instrument/RuntimeServerTest.scala
  engine/runtime/src/test/scala/org/enso/interpreter/test/semantic/StrictCompileErrorsTest.scala
  lib/pkg/src/main/scala/org/enso/pkg/Package.scala
Labels: Category: Backend, Change: Breaking, Difficulty: Core Contributor, Priority: High, Type: Enhancement

#703 Bump the Scala Version
  build.sbt
  engine/language-server/src/main/scala/org/enso/languageserver/filemanager/ReceivesTreeUpdatesHandler.scala
  engine/language-server/src/test/resources/application.conf
  engine/language-server/src/test/resources/logback-test.xml
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/data/BinaryServerTestKit.scala
  engine/language-server/src/test/scala/org/enso/languageserver/websocket/rpc/VisualisationOperationsTest.scala
  engine/runtime/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
  lib/file-manager/README.md
  lib/file-manager/src/main/scala/org/enso/FileManager.scala
  lib/file-manager/src/main/scala/org/enso/filemanager/API.scala
  lib/file-manager/src/test/scala/org/enso/filemanager/BehaviorTests.scala
  lib/file-manager/src/test/scala/org/enso/filemanager/Helpers.scala
  lib/file-manager/src/test/scala/org/enso/filemanager/WatchTests.scala
  lib/graph/src/test/scala/org/enso/graph/GraphTestDefinition.scala
  lib/json-rpc-server-test/src/main/scala/org/enso/jsonrpc/test/JsonRpcServerTestKit.scala
  lib/project-manager/src/main/scala/org/enso/projectmanager/boot/ProjectManager.scala
  lib/project-manager/src/test/resources/application.conf
  lib/project-manager/src/test/resources/logback-test.xml
  lib/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/LanguageServerSupervisorSpec.scala
  lib/project-manager/src/test/scala/org/enso/projectmanager/infrastructure/languageserver/PingMatcher.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/AST.scala
  lib/syntax/definition/src/main/scala/org/enso/syntax/text/ast/meta/Pattern.scala
  lib/syntax/specialization/shared/src/bench/scala/org/enso/syntax/DocParserBench.scala
  lib/syntax/specialization/shared/src/bench/scala/org/enso/syntax/ParserBenchmark.scala
  project/plugins.sbt
Labels: Category: External, Change: Non-Breaking, Difficulty: Core Contributor, Priority: Highest, Type: Enhancement
